### PR TITLE
Feat/UI UX

### LINKED ISSUE #19: Sheet home card
### Reason

Create the sheet home

### Description

image

- Month and lifetime values are variable inputs
- The circular progress bar reflects the month values 

### Success Criteria

- [ ] UI meets specs

### Additional Information

_No response_

### LINKED ISSUE #20: Sheet home carousel
### Reason

Create the sheet home

### Description

Create a carousel with all the accounts available for login.
The carousel items should come from an enum that holds the name, ID to be used for login, and icon.

Captura de Tela 2023-10-31 às 18 19 31

### Success Criteria

- [ ] UI meets specs

### Additional Information

_No response_

### LINKED ISSUE #21: Sheet home account grid
### Reason

Create the sheet home

### Description

when the user scrolls up the account carousel, the bottom sheet should expand and show all the accounts in a grid

Captura de Tela 2023-10-31 às 18 21 41

### Success Criteria

- [ ] UI meets specs

### Additional Information

_No response_

### LINKED ISSUE #22: More Sheet
### Reason

Create the more sheet UI

### Description

When the user taps in the "more" word in sheet home, open the "More Sheet"

- The monthly estimate comes from a list where the top 3 will be the green bars, darker, medium and lighter and the others will be the white part.
- Connected accounts are shown in a grid. if the account is not verified it should show a red exclamation icon on top.
- Report an issue should be a tappable link. Action TBD
- Data licensing agreement should show the terms
- Opt out should revoke the license

image

### Success Criteria

- [ ] UI meets specs

### Additional Information

_No response_

### LINKED ISSUE #23: Create the email account screen
### Reason

Create the email account screen for connecting an email account

### Description

This sheet should be opened when the user taps on an email account in the home sheet.
- for Gmail and outlook add the OAuth sign in button.

image

### Success Criteria

- [ ] UI meets specs

### Additional Information

_No response_

### LINKED ISSUE #24: Create the retailer account screen
### Reason

Create the retailer account screen

### Description

No account connected
image

One account connected:
image

### Success Criteria

- [ ] UI meets specs

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Schuler-Gabriel**
All UIs for CLO Demo app are ready. The Rewards API is defined and is already used in some UIs, but is missing documentation which will be done in another PR. 

Spec is in the left in the screenshots.

## Home Sheet
closes #19
closes #20
closes #21 

Screenshot 2023-11-23 at 16 23 57

Screenshot 2023-11-23 at 16 41 47

## More Sheet
closes #22 

Screenshot 2023-11-23 at 16 42 21

Screenshot 2023-11-23 at 16 42 49

## Email account screen
closes #23 

Screenshot 2023-11-23 at 16 48 43

## Retailer account screen
closes #24 

Screenshot 2023-11-23 at 16 52 57

Screenshot 2023-11-23 at 17 00 08

Screenshot 2023-11-23 at 17 01 02

### CODE REVIEW

**Comment by ricardobrg** [comment]
@Schuler-Gabriel on Email account screen
1. the google sign in oauth btn is different.
2. the google icon is with the incorrect image yet. Use the same we have in iOS.

@sfaria27 please check if you spot any differences other than these.

**Comment by sfaria27** [comment]
@ricardobrg "Opt out of cashback connections" still needs capitalization for Android. 

I also cannot see the requested changes as they are not added.

**Comment by ricardobrg** [comment]
@Schuler-Gabriel please add the screenshots with the corrections and resolve #45 too

**Comment by Schuler-Gabriel** [comment]
@sfaria27 i've updated the screenshots so you can review it

**Comment by ricardobrg** [comment]
I have created a new issue that will fix crispy images #54

**Review by ricardobrg — APPROVED** [review]

**Pull request merged**
